// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.28.3
// source: proto/books.proto

package server_grpc

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	BookServiceRoutes_GetAllBooks_FullMethodName = "/books.BookServiceRoutes/GetAllBooks"
)

// BookServiceRoutesClient is the client API for BookServiceRoutes service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type BookServiceRoutesClient interface {
	GetAllBooks(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*BookList, error)
}

type bookServiceRoutesClient struct {
	cc grpc.ClientConnInterface
}

func NewBookServiceRoutesClient(cc grpc.ClientConnInterface) BookServiceRoutesClient {
	return &bookServiceRoutesClient{cc}
}

func (c *bookServiceRoutesClient) GetAllBooks(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*BookList, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BookList)
	err := c.cc.Invoke(ctx, BookServiceRoutes_GetAllBooks_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// BookServiceRoutesServer is the server API for BookServiceRoutes service.
// All implementations must embed UnimplementedBookServiceRoutesServer
// for forward compatibility.
type BookServiceRoutesServer interface {
	GetAllBooks(context.Context, *emptypb.Empty) (*BookList, error)
	mustEmbedUnimplementedBookServiceRoutesServer()
}

// UnimplementedBookServiceRoutesServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedBookServiceRoutesServer struct{}

func (UnimplementedBookServiceRoutesServer) GetAllBooks(context.Context, *emptypb.Empty) (*BookList, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetAllBooks not implemented")
}
func (UnimplementedBookServiceRoutesServer) mustEmbedUnimplementedBookServiceRoutesServer() {}
func (UnimplementedBookServiceRoutesServer) testEmbeddedByValue()                           {}

// UnsafeBookServiceRoutesServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to BookServiceRoutesServer will
// result in compilation errors.
type UnsafeBookServiceRoutesServer interface {
	mustEmbedUnimplementedBookServiceRoutesServer()
}

func RegisterBookServiceRoutesServer(s grpc.ServiceRegistrar, srv BookServiceRoutesServer) {
	// If the following call pancis, it indicates UnimplementedBookServiceRoutesServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&BookServiceRoutes_ServiceDesc, srv)
}

func _BookServiceRoutes_GetAllBooks_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(emptypb.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BookServiceRoutesServer).GetAllBooks(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BookServiceRoutes_GetAllBooks_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BookServiceRoutesServer).GetAllBooks(ctx, req.(*emptypb.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

// BookServiceRoutes_ServiceDesc is the grpc.ServiceDesc for BookServiceRoutes service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var BookServiceRoutes_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "books.BookServiceRoutes",
	HandlerType: (*BookServiceRoutesServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetAllBooks",
			Handler:    _BookServiceRoutes_GetAllBooks_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/books.proto",
}
